#!/usr/bin/env bash
# script transfers a file from our client to a server

# set variables locally
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# check correct argument number
if [ $# -lt 3 ]; then
    echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

# transfer file
if [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" \
    "$USERNAME@$IP":~/
fi
