#!/usr/bin/env bash
# Install nginx with the following configs
#+ listens to port 80
#++ when querying nginx at root is prints "Hello World!"

sudo apt-get install
sudo apt-get install -y nginx

sudo mkdir -p /etc/nginx/html
sudo bash -c 'echo "Hello World!" > /etc/nginx/html/index.html'
sudo bash -c 'printf %s "server {
    listen      80 default_server;
    root        /etc/nginx/html;
    index       index.html index.htm;
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
