#!/usr/bin/env bash
# Install nginx with the following configs
#+ listens to port 80
#++ when querying nginx at root is prints "Hello World!"

apt-get update
apt-get install -y nginx

# Nginx listening on port 80

sed -i 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# querying Nginx at its root / with a GET request (requesting a page) using curl

cat <<EOF > /var/www/html/index.html
Hello World!
EOF

# Restart nginx
service nginx restart
