#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me redirects to
#+ another page.

apt-get update
apt-get install -y nginx


# Redirection
sed -i '/location \/redirect_me {/a \        return 301 https://www.github.com/MungaSoftwiz;' /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
