#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me redirects to
#+ another page.

sudo apt-get update
sudo apt-get install -y nginx

sed -i 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Content of index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configurationtion os the server using stream editor(sed)
sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.github.com\/MungaSoftwiz permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart nginx after config changes
sudo service nginx restart
