#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Installing Nginx
apt update
apt install nginx -y

# Index page HTML
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Redirection & custom 404 page & configure Nginx so that its HTTP response contains a custom header
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-enabled/default

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/MungaSoftwiz permanent;' /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
