#!/usr/bin/env bash
#  Install and configure HAproxy on the lb-01 server

# Installation of ubuntu-focal HAProxy
apt-get -y update
apt-get install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

# Configure HAProxy to share resources between two servers
FILEPATH="/etc/haproxy/haproxy.cfg"
CONTENT="
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 259060-web-01 54.89.182.156:80 check
    server 259060-web-02 100.25.45.217:80 check"

echo "$CONTENT" | sudo tee -a "$FILEPATH"

# Enable HAProxy to be started with init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy
service haproxy restart
