#!/usr/bin/env bash
# Creates a mysql backup dump, creates and compresses it into an archive

MYSQL_USER='root'
mysqldump -u"$MYSQL_USER" -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
