#!/usr/bin/env bash
# print Best school 10 times with a strin
# on 9th element in between

counter=1
while [[ "$counter" -le 10 ]]; do
	echo "Best School"
	if [[ "$counter" -eq 9 ]]; then
		echo "Hi"
	fi
	((counter++))
done
