#!/usr/bin/env bash
# Installs ufw firewall and applies a few rules on web-01

# Installs the ufw
apt-get install ufw

# Disables the ufw
ufw disable

# Sets default configurations
ufw default deny incoming
ufw default allow outgoing

# Sets the firewall rules
ufw allow ssh
ufw allow https
ufw allow http

# Enables ufw for configurations to take effect
ufw enable
